apiVersion: apps/v1
kind: Deployment
metadata:
  name: speckle-webhook-service
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-webhook-service
    project: speckle-server
spec:
  replicas: {{ .Values.webhook_service.replicas }}
  selector:
    matchLabels:
      app: speckle-webhook-service
      project: speckle-server
  template:
    metadata:
      labels:
        app: speckle-webhook-service
        project: speckle-server
    spec:
      containers:
      - name: main
        image: speckle/speckle-webhook-service:{{ .Values.docker_image_tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        ports:
          - name: metrics
            containerPort: 9095
            protocol: TCP

        ports:
          - name: metrics
            containerPort: 9095
            protocol: TCP

        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          exec:
            command:
              - node
              - -e
              - process.exit(Date.now() - require('fs').readFileSync('/tmp/last_successful_query', 'utf8') > 30 * 1000)

        resources:
          requests:
            cpu: {{ .Values.webhook_service.requests.cpu }}
            memory: {{ .Values.webhook_service.requests.memory }}
          limits:
            cpu: {{ .Values.webhook_service.limits.cpu }}
            memory: {{ .Values.webhook_service.limits.memory }}

        {{- if .Values.db.useCertificate }}
        volumeMounts:
          - name: postgres-certificate
            mountPath: /postgres-certificate
        {{- end }}

        env:
          - name: PG_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: postgres_url

          - name: DEBUG
            value: "webhook-service:*"

          {{- if .Values.db.useCertificate }}
          - name: NODE_EXTRA_CA_CERTS
            value: "/postgres-certificate/ca-certificate.crt"
          {{- end }}

      priorityClassName: low-priority

      # Should be > webhook max call time ( ~= 10 seconds )
      terminationGracePeriodSeconds: 30

      {{- if .Values.db.useCertificate }}
      volumes:
        - name: postgres-certificate
          configMap:
            name: postgres-certificate
      {{- end }}
