{{- if (and (.Values.fileimport_service.networkPolicy.enabled) (eq .Values.networkPlugin.type "kubernetes")) -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend.name" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "frontend.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # allow ingress from the loadbalancer
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.ingress.namespace }}
        - podSelector:
            matchLabels:
{{ include  "frontend.ingress.selector.pod" $ | indent 14 }}
      ports:
        - port: www
  egress: [] # block all egress
{{- end -}}
