apiVersion: v1
kind: Service
metadata:
  name: speckle-frontend-2
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend-2.labels" . | indent 4 }}
spec:
  selector:
    app: speckle-frontend-2
    project: speckle-server
  ports:
    - protocol: TCP
      name: www
      port: 8080
      targetPort: www
