{{- if .Values.server.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "server.name" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "server.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "server.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    # allow access to DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
{{- if .Values.server.sentry_dns }}
    # sentry.io https://docs.sentry.io/product/security/ip-ranges/#event-ingestion
    - to:
      - ipBlock:
          cidr: 34.120.195.249/32
      ports:
        - port: 443
{{- end }}
    # redis
{{ include "speckle.networkpolicy.egress.redis" $ | indent 4 }}
    # postgres
{{ include "speckle.networkpolicy.egress.postgres" $ | indent 4 }}
    # blob storage
{{ include "speckle.networkpolicy.egress.blob_storage" $ | indent 4 }}
  ingress:
    # allow ingress from the loadbalancer (nginx ingress)
    - from:
        - namespaceSelector: {}
      ports:
        - port: http
    # allow ingress from the fileimport service
    - from:
        - podSelector:
            matchLabels:
{{ include "fileimport_service.selectorLabels" $ | indent 14}}
      ports:
        - port: http
{{- if .Values.helm_test_enabled }}
    # allow ingress from the test
    - from:
        - podSelector:
            matchLabels:
{{ include "test.selectorLabels" $ | indent 14}}
{{- end }}
{{- end -}}
