apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "server.labels" . | indent 4 }}
spec:
  selector:
{{ include "server.selectorLabels" . | indent 4 }}
  ports:
    - name: web
      port: 3000
      protocol: TCP
      targetPort: http
