{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "server.name" $ }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "server.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
secrets:
{{- include "server.serviceAccountSecrets" $ | indent 2 }}
{{- end -}}
