{{- if .Values.objects.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "objects.name" $ }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "objects.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
secrets:
  - name: {{ default .Values.secretName .Values.db.connectionString.secretName }}
  - name: {{ default .Values.secretName .Values.redis.connectionString.secretName }}
  - name: {{ default .Values.secretName .Values.s3.secret_key.secretName }}
  - name: {{ default .Values.secretName .Values.server.sessionSecret.secretName }}
{{- if .Values.server.auth.google.enabled }}
  - name: {{ default .Values.secretName .Values.server.auth.google.clientSecret.secretName }}
{{- end }}
{{- if .Values.server.auth.github.enabled }}
  - name: {{ default .Values.secretName .Values.server.auth.github.clientSecret.secretName }}
{{- end }}
{{- if .Values.server.auth.azure_ad.enabled }}
  - name: {{ default .Values.secretName .Values.server.auth.azure_ad.clientSecret.secretName }}
{{- end }}
{{- if .Values.server.auth.oidc.enabled }}
  - name: {{ default .Values.secretName .Values.server.auth.oidc.clientSecret.secretName }}
{{- end }}
{{- if .Values.server.email.enabled }}
  - name: {{ default .Values.secretName .Values.server.email.password.secretName }}
{{- end }}
{{- if .Values.server.monitoring.apollo.enabled }}
  - name: {{ default .Values.secretName .Values.server.monitoring.apollo.key.secretName }}
{{- end }}
{{- if .Values.featureFlags.automateModuleEnabled }}
  - name: encryption-keys
{{- end }}
{{- if .Values.featureFlags.workspaceModuleEnabled }}
  - name: {{ default .Values.secretName .Values.server.licenseTokenSecret.secretName }}
{{- end }}
{{- if .Values.featureFlags.workspacesMultiRegionEnabled }}
  - name: {{ default .Values.secretName .Values.multiRegion.config.secretName }}
{{- end }}
{{- end -}}
