{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: speckle-objects
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels" . | indent 4 }}
# There is no equivalent of nginx.ingress.kubernetes.io/proxy-body-size for Gateway API
spec:
  parentRefs:
    - name: {{ .Values.gatewayAPI.gateway.name }}
      {{- if .Values.gatewayAPI.gateway.namespace }}
      namespace: {{ .Values.gatewayAPI.gateway.namespace }}
      {{- end }}
      sectionName: {{ .Values.gatewayAPI.gateway.defaultListenerName }}
  hostnames:
    - {{ .Values.domain | quote}}
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /api/
      - path:
          type: PathPrefix
          value: /preview/
      - path:
          type: PathPrefix
          value: "/api/getobjects/"
      - path:
          type: PathPrefix
          value: "/api/objects/"
      - path:
          type: PathPrefix
          value: "/api/diff/"
      - path:
          type: PathPrefix
          value: "/objects/"
      - path:
          type: PathPrefix
          value: "/api/file/"
      - path:
          type: PathPrefix
          value: "/api/stream/"
      - path:
          type: PathPrefix
          value: "/api/thirdparty/gendo"
    backendRefs:
      - name: speckle-objects
        kind: Service
        port: 3000

{{- end }}
