{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: speckle-redirects
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels" . | indent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayAPI.gateway.name }}
      {{- if .Values.gatewayAPI.gateway.namespace }}
      namespace: {{ .Values.gatewayAPI.gateway.namespace }}
      {{- end }}
      sectionName: {{ .Values.gatewayAPI.gateway.defaultListenerName }}
  hostnames:
    - {{ .Values.domain | quote}}
  rules:
    - matches:
        - path:
            type: Exact
            value: /metrics
        - path:
            type: Exact
            value: /api/status
        - path:
            type: Exact
            value: /liveness
        - path:
            type: Exact
            value: /readiness
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /
      backendRefs:
        - name: speckle-frontend-2
          kind: Service
          port: 8080
{{- end }}
