{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: speckle-server
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels" . | indent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayAPI.gateway.name }}
      {{- if .Values.gatewayAPI.gateway.namespace }}
      namespace: {{ .Values.gatewayAPI.gateway.namespace }}
      {{- end }}
      sectionName: {{ .Values.gatewayAPI.gateway.defaultListenerName }}
  hostnames:
    - {{ .Values.domain | quote }}
  rules:
  - matches:
      - path:
          type: Exact
          value: "/graphql"
      - path:
          type: Exact
          value: "/explorer"
      - path:
          type: PathPrefix
          value: "/auth/"
      - path:
          type: PathPrefix
          value: "/static/"
    backendRefs:
      - name: speckle-server
        kind: Service
        port: 3000
{{- end }}
