{{- if .Values.webhook_service.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook_service.name" $ }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "webhook_service.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
secrets:
  - name: {{ .Values.secretName }}
{{- end -}}
