name: Move new issues into Project

on:
  issues:
    types: [opened]

jobs:
  track_issue:
    uses: specklesystems/github-actions/.github/workflows/project-add-issue.yml@main
    secrets: inherit
    with:
      issue-id: ${{ github.event.issue.node_id }}